# Generated by Django 5.0.6 on 2025-02-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("vendor", "Vendor"),
                    ("customer", "Customer"),
                ],
                max_length=10,
            ),
        ),
    ]
