# Generated by Django 5.0.6 on 2025-02-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("signup", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Catering", "Catering"),
                    ("Florist", "Florist"),
                    ("Decoration", "Decoration"),
                    ("Lighting", "Lighting"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Vendor", "Vendor"),
                    ("Customer", "Customer"),
                ],
                max_length=10,
            ),
        ),
    ]
