# Generated by Django 5.0.6 on 2025-02-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="category",
            field=models.CharField(
                choices=[
                    ("Catering", "Catering"),
                    ("Florist", "Florist"),
                    ("Decoration", "Decoration"),
                    ("Lighting", "Lighting"),
                ],
                default="Catering",
                max_length=50,
            ),
        ),
    ]
